//
//  WimModel.h
//  virsualwim
//
//  Created by pawit on 9/6/2557 BE.
//  Copyright (c) 2557 Department of Highways. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface WimModel : NSObject{

    NSInteger WIMID;
    NSInteger StationID;
    NSString *TimeStamp;
    NSString *VehicleNumber;
    NSString *Lane;
    NSString *Error;
    NSString *StatusCode;
    NSString *GVW;
    NSString *MaxGVW;
    NSString *ESAL;
    NSString *Speed;
    NSString *AxleCount;
    NSString *Axle01Seperation;
    NSString *Axle01Weight;
    NSString *Axle01Max;
    NSString *Axle01Group;
    NSString *Axle01TireCode;
    NSString *Axle02Seperation;
    NSString *Axle02Weight;
    NSString *Axle02Max;
    NSString *Axle02Group;
    NSString *Axle02TireCode;
    NSString *Axle03Seperation;
    NSString *Axle03Weight;
    NSString *Axle03Max;
    NSString *Axle03Group;
    NSString *Axle03TireCode;
    NSString *Axle04Seperation;
    NSString *Axle04Weight;
    NSString *Axle04Max;
    NSString *Axle04Group;
    NSString *Axle04TireCode;
    NSString *Axle05Seperation;
    NSString *Axle05Weight;
    NSString *Axle05Max;
    NSString *Axle05Group;
    NSString *Axle05TireCode;
    NSString *Axle06Seperation;
    NSString *Axle06Weight;
    NSString *Axle06Max;
    NSString *Axle06Group;
    NSString *Axle06TireCode;
    NSString *Axle07Seperation;
    NSString *Axle07Weight;
    NSString *Axle07Max;
    NSString *Axle07Group;
    NSString *Axle07TireCode;
    NSString *Axle08Seperation;
    NSString *Axle08Weight;
    NSString *Axle08Max;
    NSString *Axle08Group;
    NSString *Axle08TireCode;
    NSString *Axle09Seperation;
    NSString *Axle09Weight;
    NSString *Axle09Max;
    NSString *Axle09Group;
    NSString *Axle09TireCode;
    NSString *Axle10Seperation;
    NSString *Axle10Weight;
    NSString *Axle10Max;
    NSString *Axle10Group;
    NSString *Axle10TireCode;
    NSString *Axle11Seperation;
    NSString *Axle11Weight;
    NSString *Axle11Max;
    NSString *Axle11Group;
    NSString *Axle11TireCode;
    NSString *Axle12Seperation;
    NSString *Axle12Weight;
    NSString *Axle12Max;
    NSString *Axle12Group;
    NSString *Axle12TireCode;
    NSString *Axle13Seperation;
    NSString *Axle13Weight;
    NSString *Axle13Max;
    NSString *Axle13Group;
    NSString *Axle13TireCode;
    NSString *Axle14Seperation;
    NSString *Axle14Weight;
    NSString *Axle14Max;
    NSString *Axle14Group;
    NSString *Axle14TireCode;
    NSString *Length;
    NSString *FrontOverHang;
    NSString *RearOverHang;
    NSString *VehicleType;
    NSString *VehicleClass;
    NSString *RecordType;
    NSString *ImageCount;
    NSString *Image01Name;
    NSString *Image02Name;
    NSString *Image03Name;
    NSString *Image04Name;
    NSString *Image05Name;
    NSString *Image06Name;
    NSString *Image07Name;
    NSString *Image08Name;
    NSString *Image09Name;
    NSString *Image10Name;
    NSString *SortDecision;
    NSString *LicensePlateNumber;
    NSString *LicensePlateProvinceID;
    NSString *LicensePlateImageName;
    NSString *LicensePlateConfidence;
    NSString *StatusColor;
    NSString *ProvinceName;
    NSString *StationName;
    NSString *TimeStampLong;
}

@property (nonatomic) NSInteger WIMID;
@property (nonatomic) NSInteger StationID;
@property (nonatomic, retain) NSString *TimeStamp;
@property (nonatomic, retain) NSString *VehicleNumber;
@property (nonatomic, retain) NSString *Lane;
@property (nonatomic, retain) NSString *Error;
@property (nonatomic, retain) NSString *StatusCode;
@property (nonatomic, retain) NSString *GVW;
@property (nonatomic, retain) NSString *MaxGVW;
@property (nonatomic, retain) NSString *ESAL;
@property (nonatomic, retain) NSString *Speed;
@property (nonatomic, retain) NSString *AxleCount;
@property (nonatomic, retain) NSString *Axle01Seperation;
@property (nonatomic, retain) NSString *Axle01Weight;
@property (nonatomic, retain) NSString *Axle01Max;
@property (nonatomic, retain) NSString *Axle01Group;
@property (nonatomic, retain) NSString *Axle01TireCode;
@property (nonatomic, retain) NSString *Axle02Seperation;
@property (nonatomic, retain) NSString *Axle02Weight;
@property (nonatomic, retain) NSString *Axle02Max;
@property (nonatomic, retain) NSString *Axle02Group;
@property (nonatomic, retain) NSString *Axle02TireCode;
@property (nonatomic, retain) NSString *Axle03Seperation;
@property (nonatomic, retain) NSString *Axle03Weight;
@property (nonatomic, retain) NSString *Axle03Max;
@property (nonatomic, retain) NSString *Axle03Group;
@property (nonatomic, retain) NSString *Axle03TireCode;
@property (nonatomic, retain) NSString *Axle04Seperation;
@property (nonatomic, retain) NSString *Axle04Weight;
@property (nonatomic, retain) NSString *Axle04Max;
@property (nonatomic, retain) NSString *Axle04Group;
@property (nonatomic, retain) NSString *Axle04TireCode;
@property (nonatomic, retain) NSString *Axle05Seperation;
@property (nonatomic, retain) NSString *Axle05Weight;
@property (nonatomic, retain) NSString *Axle05Max;
@property (nonatomic, retain) NSString *Axle05Group;
@property (nonatomic, retain) NSString *Axle05TireCode;
@property (nonatomic, retain) NSString *Axle06Seperation;
@property (nonatomic, retain) NSString *Axle06Weight;
@property (nonatomic, retain) NSString *Axle06Max;
@property (nonatomic, retain) NSString *Axle06Group;
@property (nonatomic, retain) NSString *Axle06TireCode;
@property (nonatomic, retain) NSString *Axle07Seperation;
@property (nonatomic, retain) NSString *Axle07Weight;
@property (nonatomic, retain) NSString *Axle07Max;
@property (nonatomic, retain) NSString *Axle07Group;
@property (nonatomic, retain) NSString *Axle07TireCode;
@property (nonatomic, retain) NSString *Axle08Seperation;
@property (nonatomic, retain) NSString *Axle08Weight;
@property (nonatomic, retain) NSString *Axle08Max;
@property (nonatomic, retain) NSString *Axle08Group;
@property (nonatomic, retain) NSString *Axle08TireCode;
@property (nonatomic, retain) NSString *Axle09Seperation;
@property (nonatomic, retain) NSString *Axle09Weight;
@property (nonatomic, retain) NSString *Axle09Max;
@property (nonatomic, retain) NSString *Axle09Group;
@property (nonatomic, retain) NSString *Axle09TireCode;
@property (nonatomic, retain) NSString *Axle10Seperation;
@property (nonatomic, retain) NSString *Axle10Weight;
@property (nonatomic, retain) NSString *Axle10Max;
@property (nonatomic, retain) NSString *Axle10Group;
@property (nonatomic, retain) NSString *Axle10TireCode;
@property (nonatomic, retain) NSString *Axle11Seperation;
@property (nonatomic, retain) NSString *Axle11Weight;
@property (nonatomic, retain) NSString *Axle11Max;
@property (nonatomic, retain) NSString *Axle11Group;
@property (nonatomic, retain) NSString *Axle11TireCode;
@property (nonatomic, retain) NSString *Axle12Seperation;
@property (nonatomic, retain) NSString *Axle12Weight;
@property (nonatomic, retain) NSString *Axle12Max;
@property (nonatomic, retain) NSString *Axle12Group;
@property (nonatomic, retain) NSString *Axle12TireCode;
@property (nonatomic, retain) NSString *Axle13Seperation;
@property (nonatomic, retain) NSString *Axle13Weight;
@property (nonatomic, retain) NSString *Axle13Max;
@property (nonatomic, retain) NSString *Axle13Group;
@property (nonatomic, retain) NSString *Axle13TireCode;
@property (nonatomic, retain) NSString *Axle14Seperation;
@property (nonatomic, retain) NSString *Axle14Weight;
@property (nonatomic, retain) NSString *Axle14Max;
@property (nonatomic, retain) NSString *Axle14Group;
@property (nonatomic, retain) NSString *Axle14TireCode;
@property (nonatomic, retain) NSString *Length;
@property (nonatomic, retain) NSString *FrontOverHang;
@property (nonatomic, retain) NSString *RearOverHang;
@property (nonatomic, retain) NSString *VehicleType;
@property (nonatomic, retain) NSString *VehicleClass;
@property (nonatomic, retain) NSString *RecordType;
@property (nonatomic, retain) NSString *ImageCount;
@property (nonatomic, retain) NSString *Image01Name;
@property (nonatomic, retain) NSString *Image02Name;
@property (nonatomic, retain) NSString *Image03Name;
@property (nonatomic, retain) NSString *Image04Name;
@property (nonatomic, retain) NSString *Image05Name;
@property (nonatomic, retain) NSString *Image06Name;
@property (nonatomic, retain) NSString *Image07Name;
@property (nonatomic, retain) NSString *Image08Name;
@property (nonatomic, retain) NSString *Image09Name;
@property (nonatomic, retain) NSString *Image10Name;
@property (nonatomic, retain) NSString *SortDecision;
@property (nonatomic, retain) NSString *LicensePlateNumber;
@property (nonatomic, retain) NSString *LicensePlateProvinceID;
@property (nonatomic, retain) NSString *LicensePlateImageName;
@property (nonatomic, retain) NSString *LicensePlateConfidence;
@property (nonatomic, retain) NSString *StatusColor;
@property (nonatomic, retain) NSString *ProvinceName;
@property (nonatomic, retain) NSString *StationName;
@property (nonatomic, retain) NSString *TimeStampLong;
@end